//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_VMedProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppointmentID { get; set; }
        public int DoctorID { get; set; }
        public int ServiceID { get; set; }
        public string UserId { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public string Notes { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Service Service { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
