//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_VMedProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int RatingID { get; set; }
        public int DoctorID { get; set; }
        public decimal RatingValue { get; set; }
        public string Comment { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
